language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov

script:
  - pytest --cov-report=xml --cov=densityestimation tests/

after_success:
  - codecov